### ISSUE TITLE
Use ES6 classes

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Flappy-Bird-Clone#2]
The `Pipe` and `Bird` should be re-written to be ES6 classes.

**Comment by techiepriyansh** [comment]
Hey Dan!!! I fixed the pipe spacing. It now matches with the original game. Also updated the syntax to ES6. You can access the code here https://drive.google.com/file/d/1ijRWYSfMuTbvYv1Vd-nUOPuCbJKBoXek/view?usp=drivesdk

(I am not comfortable with gitting....!!!)
