### ISSUE TITLE
Pipe design

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Flappy-Bird-Clone#24]
They look like maybe they are too close together and too skinny? (As compared to the original game design?)

**Comment by shiffman** [comment]
Maybe #23 fixes this?

**Comment by rhbvkleef** [comment]
That is a consideration for you to make. I kind of like the design in #23 (given it does what I think it does). I would say it does fix this. In the end this is a case of do you like it or not, if you do: issue closed.

**Comment by DaGuT** [comment]
https://github.com/CodingTrain/Flappy-Bird-Clone/pull/25
Done :)

**Comment by ZwergB** [comment]
The collision detection is still a bit off. Both the "Flappy" train and the pipes have little transparent pieces on their right and left side.

To see it better, the following picture shows the first frame of collision with the pipe.

![collision_flappytrain](https://user-images.githubusercontent.com/12022933/37314894-f05e7c5a-2656-11e8-8e1d-d0684ad1f32f.png)

We have to either cut the transparent pieces from the pictures or modify the collision detection by some arbitrary numbers (which is probably the worse idea).

**Comment by DaGuT** [comment]
https://github.com/CodingTrain/Flappy-Bird-Clone/pull/31
Pipe problem is fixed in here with new pipe from some1's commit

Train.... Yeah, may be some1 wants to fix it, idk :)

**Comment by shiffman** [comment]
Leaving this open as I think I'd like to implement a custom / original design in case there are copyright issues with the green ones.

**Comment by DaGuT** [comment]
@shiffman https://github.com/CodingTrain/Flappy-Bird-Clone/pull/31 there was custom design, It was open for quite a while. Do it :D

**Comment by A-Edusei** [comment]
I noticed this issue is still open and I've gone ahead to implement some design ideas. I hope these will be suited to the design needs of the game. Issue addressed in #43

**Comment by shiffman** [comment]
Resolved!
