### ISSUE TITLE
Visual / Game Design

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Flappy-Bird-Clone#4]
Why is this a 400x600 canvas? That seems weird. And the graphics are terrible. How about some Coding Train themed sprites and colors? 

The code should be kept simple because the point is to demonstrate neuro-evolution but it'll be more fun if it has more personality and resembles the original game.

**Comment by WakeMeAtThree** [comment]
I'll get started on that tonight.

**Comment by KeeghanM** [comment]
Changed the "bird" to the coding train train, and added a scrolling background. Maybe the pipes should be unicorn horns? That can come later though.

**Comment by WakeMeAtThree** [comment]
I made a visual mockup (modified an existing map) for the background with the pipes to test our possible color combinations (and added a faint hint of this . dot in the background ;) ) I'll be reworking them a bit more and separating the layers to be used as tiles in the game.

![visualmockup](https://user-images.githubusercontent.com/33008158/37213737-5ce4eeaa-23cc-11e8-800d-4bdd34fb6939.jpg)

**Comment by shiffman** [comment]
Closing thanks to contributions, will open specific issues!
